repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 24.2.0  # Latest Black formatter version
    hooks:
      - id: black
        args: ["--line-length=88"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Latest Flake8 version
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear"]

  - repo: local
    hooks:
      - id: check-migrations
        name: Check if database migrations are needed
        entry: ./scripts/check_migrations.sh
        language: system
        pass_filenames: false

      - id: pytest
        name: Run tests with pytest
        entry: pytest tests --maxfail=1 -v
        language: system
        pass_filenames: false
