"""Added access group; removed language-related attributes of user model

Revision ID: 0a214e680172
Revises: c273b27d09aa
Create Date: 2025-02-26 12:22:13.207712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a214e680172'
down_revision = 'c273b27d09aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_group', sa.String(length=255), nullable=True))
        batch_op.drop_column('target_language')
        batch_op.drop_column('native_language')
        batch_op.drop_column('proficiency_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proficiency_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('native_language', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('target_language', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('access_group')

    # ### end Alembic commands ###
