"""Recreate database

Revision ID: 0b451fa7c4ec
Revises: 0b818736b7cd
Create Date: 2025-02-07 14:30:06.409722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b451fa7c4ec'
down_revision = '0b818736b7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=100), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_time', sa.Integer(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_cases_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_cases_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('first_name_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('last_name_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('class_name', sa.String(length=255), nullable=True),
    sa.Column('is_student', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('native_language', sa.String(length=50), nullable=True),
    sa.Column('target_language', sa.String(length=50), nullable=True),
    sa.Column('proficiency_level', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_encrypted')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('practice_case_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('proficiency_level', sa.String(length=50), nullable=True),
    sa.Column('scenario_context', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['practice_case_id'], ['practice_cases.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_id'))

    op.drop_table('messages')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_id'))

    op.drop_table('conversations')
    op.drop_table('users')
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_cases_id'))
        batch_op.drop_index(batch_op.f('ix_practice_cases_class_name'))

    op.drop_table('practice_cases')
    # ### end Alembic commands ###
