"""Remove user_id from PracticeCase

Revision ID: 0b818736b7cd
Revises: 9f03f38b1857
Create Date: 2025-02-07 13:37:06.721435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b818736b7cd'
down_revision = '9f03f38b1857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_cases_class_name'), ['class_name'], unique=False)
        batch_op.drop_constraint('practice_cases_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('practice_cases_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_practice_cases_class_name'))

    # ### end Alembic commands ###
