"""Added voice and language to practice case

Revision ID: 156e8b7ce6ad
Revises: a1ea88c4085d
Create Date: 2025-03-05 21:57:42.176505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156e8b7ce6ad'
down_revision = 'a1ea88c4085d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('language_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.drop_column('language_code')
        batch_op.drop_column('voice')

    # ### end Alembic commands ###
