"""Added Published and Accessible On properties to practice cases

Revision ID: 16c7e36b3914
Revises: 82506d30bf72
Create Date: 2025-02-22 14:00:21.396873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c7e36b3914'
down_revision = '82506d30bf72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('accessible_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.drop_column('accessible_on')
        batch_op.drop_column('published')

    # ### end Alembic commands ###
