"""Added cultural context

Revision ID: 37fa48ce183a
Revises: 3b51b0e3bc92
Create Date: 2025-08-01 16:02:30.189040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37fa48ce183a'
down_revision = '3b51b0e3bc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cultural_context', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.drop_column('cultural_context')

    # ### end Alembic commands ###
