"""Adding image storing functionality

Revision ID: 3b51b0e3bc92
Revises: 5554b182752f
Create Date: 2025-07-30 13:24:46.203536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b51b0e3bc92'
down_revision = '5554b182752f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_case_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('practice_case_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['practice_case_id'], ['practice_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_case_images')
    # ### end Alembic commands ###
