"""Add fields to PracticeCase model

Revision ID: 45e6313140c6
Revises: 10caa6a448b7
Create Date: 2025-02-03 11:16:58.284851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e6313140c6'
down_revision = '10caa6a448b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('class_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('system_prompt', sa.Text(), nullable=False))
        batch_op.drop_column('language')
        batch_op.drop_column('objectives')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objectives', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('system_prompt')
        batch_op.drop_column('class_name')
        batch_op.drop_column('institution')

    # ### end Alembic commands ###
