"""Added class section, is registered, and access group

Revision ID: 47c47b8a7ad8
Revises: 989fe77d9f92
Create Date: 2025-03-03 17:30:44.788335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c47b8a7ad8'
down_revision = '989fe77d9f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_registered', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_registered')
        batch_op.drop_column('section')

    # ### end Alembic commands ###
