"""Change practice case model creation column

Revision ID: 5204bc908edf
Revises: 52cd9ea0d2ea
Create Date: 2025-05-23 13:49:46.926998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5204bc908edf'
down_revision = '52cd9ea0d2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
