"""Updated practice case model

Revision ID: 52cd9ea0d2ea
Revises: 0358c30d6655
Create Date: 2025-05-23 13:45:42.699479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cd9ea0d2ea'
down_revision = 'e9dbcfe3aaf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_section_enrollment', ['user_id', 'section_id'])

    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_section_enrollment', type_='unique')

    # ### end Alembic commands ###
