"""Adding feedback models for tracking conversations with feedback engine

Revision ID: 5554b182752f
Revises: 58ce23d4124d
Create Date: 2025-07-16 12:25:17.086600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5554b182752f'
down_revision = '58ce23d4124d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('summary_feedback', sa.Text(), nullable=True),
    sa.Column('detailed_feedback', sa.Text(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['original_conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_conversations_id'), ['id'], unique=False)

    op.create_table('feedback_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('is_suggestion', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_conversation_id'], ['feedback_conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_messages_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_messages_id'))

    op.drop_table('feedback_messages')
    with op.batch_alter_table('feedback_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_conversations_id'))

    op.drop_table('feedback_conversations')
    # ### end Alembic commands ###
