"""Adding speed parameters

Revision ID: 6c495e993617
Revises: 9c05d5841f15
Create Date: 2025-08-08 13:02:46.917325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c495e993617'
down_revision = '9c05d5841f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speaking_speed', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.drop_column('speaking_speed')

    # ### end Alembic commands ###
