"""Added survey completion flag to user model

Revision ID: 8018ac95ecfb
Revises: e227861ea616
Create Date: 2025-03-10 18:03:07.892677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8018ac95ecfb'
down_revision = 'e227861ea616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_completed_survey', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_completed_survey')

    # ### end Alembic commands ###
