"""Added completed property to conversation

Revision ID: 82506d30bf72
Revises: f4535c1c5f55
Create Date: 2025-02-12 16:52:25.697999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82506d30bf72'
down_revision = 'f4535c1c5f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
