"""Global case library

Revision ID: 9c05d5841f15
Revises: 37fa48ce183a
Create Date: 2025-08-04 16:31:59.867785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c05d5841f15'
down_revision = '37fa48ce183a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_to_library', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('library_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('library_submitted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('library_approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('library_approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('author_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('author_institution', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('library_tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('library_downloads', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('library_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('library_rating_count', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['library_approved_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('library_rating_count')
        batch_op.drop_column('library_rating')
        batch_op.drop_column('library_downloads')
        batch_op.drop_column('library_tags')
        batch_op.drop_column('author_institution')
        batch_op.drop_column('author_name')
        batch_op.drop_column('library_approved_by')
        batch_op.drop_column('library_approved_at')
        batch_op.drop_column('library_submitted_at')
        batch_op.drop_column('library_approved')
        batch_op.drop_column('submitted_to_library')

    # ### end Alembic commands ###
