"""Added institution and class name

Revision ID: 9f03f38b1857
Revises: 45e6313140c6
Create Date: 2025-02-04 21:13:39.841034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f03f38b1857'
down_revision = '45e6313140c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('class_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('class_name')
        batch_op.drop_column('institution')

    # ### end Alembic commands ###
