"""Got rid of profiency level and scenario context from conversation

Revision ID: a1ea88c4085d
Revises: 4bdc37dd9c84
Create Date: 2025-03-05 21:39:54.126492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ea88c4085d'
down_revision = '4bdc37dd9c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('scenario_context')
        batch_op.drop_column('proficiency_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proficiency_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scenario_context', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
