"""empty message

Revision ID: a393237cfdf5
Revises: bcd612e84870
Create Date: 2025-10-13 21:52:15.315251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a393237cfdf5'
down_revision = 'bcd612e84870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.alter_column('section_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.alter_column('section_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
