"""Adding notes for students

Revision ID: aa02076fdf8e
Revises: 6c495e993617
Create Date: 2025-08-12 15:02:52.758999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa02076fdf8e'
down_revision = '6c495e993617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes_for_students', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.drop_column('notes_for_students')

    # ### end Alembic commands ###
