"""Added survey model

Revision ID: b3c5626c4445
Revises: f29954fd4384
Create Date: 2025-03-09 21:45:17.930619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c5626c4445'
down_revision = 'f29954fd4384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_redirects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('survey_type', sa.String(length=50), nullable=False),
    sa.Column('redirected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_redirects')
    # ### end Alembic commands ###
