"""Add model and version metadata

Revision ID: bcd612e84870
Revises: db6c449cb2a4
Create Date: 2025-08-14 14:54:58.365142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd612e84870'
down_revision = 'db6c449cb2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('feedback_version', sa.String(length=50), nullable=True))
        batch_op.drop_column('engagement_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engagement_score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('feedback_version')
        batch_op.drop_column('model')

    # ### end Alembic commands ###
