"""Removed lesson number; added feedback prompt to practice case model

Revision ID: c273b27d09aa
Revises: 7d1ccead407b
Create Date: 2025-02-25 14:17:58.544295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c273b27d09aa'
down_revision = '7d1ccead407b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_prompt', sa.Text(), nullable=True))
        batch_op.drop_column('lesson_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_number', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('feedback_prompt')

    # ### end Alembic commands ###
