"""Add feedback config for JSON feedback

Revision ID: db6c449cb2a4
Revises: aa02076fdf8e
Create Date: 2025-08-14 14:53:31.976245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6c449cb2a4'
down_revision = 'aa02076fdf8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.drop_column('feedback_config')

    # ### end Alembic commands ###
