"""Upgrade user model

Revision ID: e227861ea616
Revises: 7132d4c5499d
Create Date: 2025-03-10 17:13:17.257972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e227861ea616'
down_revision = '7132d4c5499d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('survey_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responses_encrypted', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('survey_redirects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_redirects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('survey_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('redirected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='survey_redirects_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='survey_redirects_pkey')
    )
    op.drop_table('surveys')
    # ### end Alembic commands ###
