"""Added consent properties to user model

Revision ID: f29954fd4384
Revises: 
Create Date: 2025-03-09 19:15:42.192529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29954fd4384'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_consented', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('consent_date', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('consent_date')
        batch_op.drop_column('has_consented')

    # ### end Alembic commands ###
