"""Add min-time to practice case

Revision ID: f4535c1c5f55
Revises: 0b451fa7c4ec
Create Date: 2025-02-08 14:29:21.286591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4535c1c5f55'
down_revision = '0b451fa7c4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_cases', schema=None) as batch_op:
        batch_op.drop_column('min_time')

    # ### end Alembic commands ###
